### ISSUE TITLE
Upgrade to Font Awesome v5 (Free)

### ISSUE THREAD

**Issue by thinkh** [phovea/phovea_ui#121]
Currently, we are using Font Awesome v4, but should upgrade to Font Awesome v5 (Free).

See https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

**Comment by thinkh** [comment]
The following search (and replaces) have been performed:

- Search for `fa ` (note the additional trailing space)
   - Should find `<i class="fa fa-user">...`
   - Manually go through the search results and check the icon names, i.e. `fa-user` if [they must be upgraded](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes)
   - Replace the `fa` with `fas` (only in rare cases use `far`)
- Search for `fa-`
   - Should find `fa-user` as variable in TS code
   - Manually go through the search results and check the icon names, i.e. `fa-user` if [they must be upgraded](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes) 
- Search for `.fa`
   - Should find CSS rules like `.fa { ... }`
   - Replace with `.fas`
- Search for `@include fa-icon();`
   - Should find hits in SCSS where icons are directly used in `::before`
     ```scss
     ::before {
        @include fa-icon();
        content: $fa-var-eye-slash;
     }
     ```
   - Replace with 
      ```scss
      ::before {
         @extend .fas;
         content: fa-content($fa-var-eye-slash);
      }
      ```
     Note: That the `@extend .fas;` might not be necessary!
